-- -- lua/plugins/copilot.lua
-- return {
--     {
--       "zbirenbaum/copilot.lua",
--       event = "InsertEnter",
--       config = function()
--         require("copilot").setup({
--           suggestion = { enabled = false }, -- se quiser tudo via cmp
--           panel = { enabled = false },
--         })
--       end,
--     },
--     {
--       "zbirenbaum/copilot-cmp",
--       dependencies = {
--         "zbirenbaum/copilot.lua",
--       },
--       config = function()
--         require("copilot_cmp").setup()
--       end,
--     },
--   }
  return {}